---

- name: set proxy information in bashrc
  lineinfile:
    path: ~/.bashrc
    state: present
    create: yes
    line: "{{ item }}"
  loop:
    - "export http_proxy=http://{{ webproxy_host }}:8080"
    - "export https_proxy=http://{{ webproxy_host }}:8080"

- name: add bash_profile dotfile
  copy:
    content: |
              # .bash_profile

              # Get the aliases and functions
              if [ -f ~/.bashrc ]; then
              	. ~/.bashrc
              fi

              # User specific environment and startup programs
    dest: ~/.bash_profile
    state: present

- name: set PATH in bashrc
  lineinfile:
    path: ~/.bashrc
    state: present
    create: yes
    line: "{{ item }}"
  loop:
    -  "export PATH=${PATH}:~/.local/bin/"

- name: install python lib dependencies
  pip:
    name: tox
  environment:
    HTTP_PROXY: "http://{{ webproxy_host }}:8080"
    HTTPS_PROXY: "http://{{ webproxy_host }}:8080"

- name: create wmf subdir in home folder
  file:
    path: ~/wmf
    state: directory

- name: clone spicerack repo
  git:
    repo: https://github.com/wikimedia/operations-software-spicerack.git
    dest: ~/wmf/spicerack
  environment:
    http_proxy: "http://{{ webproxy_host }}:8080"
    https_proxy: "http://{{ webproxy_host }}:8080"

- name: clone cookbooks repo
  git:
    repo: https://github.com/wikimedia/operations-cookbooks.git
    dest: ~/wmf/spicerack/cookbooks
  environment:
    http_proxy: "http://{{ webproxy_host }}:8080"
    https_proxy: "http://{{ webproxy_host }}:8080"
